### ISSUE TITLE
搜索功能不能用吗？？？

### ISSUE THREAD

**Issue by zsesz110** [debug-code-healer/CN-Chevereto#2]
看了好几个这个开源框架搭建的网站（包括官网的[demo](https://demo.chevereto.com/images/2020/04/19/_20200420004328.png)），搜索功能都是无效的
那为什么还要放一个搜索在主页上呢。。。

**Comment by Drew233** [comment]
可以用的啊
![Snipaste_2020-05-27_10-04-41.png](https://i.loli.net/2020/05/27/Jzu7yg4ZFxTe5KV.png)
